/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    IconCommunity: typeof import('./src/components/icons/IconCommunity.vue')['default']
    IconDocumentation: typeof import('./src/components/icons/IconDocumentation.vue')['default']
    IconEcosystem: typeof import('./src/components/icons/IconEcosystem.vue')['default']
    IconSupport: typeof import('./src/components/icons/IconSupport.vue')['default']
    IconTooling: typeof import('./src/components/icons/IconTooling.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    TAside: typeof import('tdesign-vue-next')['Aside']
    TButton: typeof import('tdesign-vue-next')['Button']
    TCard: typeof import('tdesign-vue-next')['Card']
    TContent: typeof import('tdesign-vue-next')['Content']
    TDialog: typeof import('tdesign-vue-next')['Dialog']
    TForm: typeof import('tdesign-vue-next')['Form']
    TFormItem: typeof import('tdesign-vue-next')['FormItem']
    THeader: typeof import('tdesign-vue-next')['Header']
    TInput: typeof import('tdesign-vue-next')['Input']
    TLayout: typeof import('tdesign-vue-next')['Layout']
    TMenu: typeof import('tdesign-vue-next')['Menu']
    TMenuItem: typeof import('tdesign-vue-next')['MenuItem']
    TOption: typeof import('tdesign-vue-next')['Option']
    TSelect: typeof import('tdesign-vue-next')['Select']
    TSubmenu: typeof import('tdesign-vue-next')['Submenu']
    TTable: typeof import('tdesign-vue-next')['Table']
  }
}
